version: 2
project_name: sketch

# Build configuration
before:
  hooks:
    - make clean

builds:
  - id: sketch
    # Note: this build corresponds to build/outie.sh; please keep them in sync.
    main: ./cmd/sketch
    binary: sketch
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    tags:
      - outie
    ldflags:
      - -X main.release={{.Version}}
      - -X main.builtBy=goreleaser
    env:
      - SKETCH_VERSION={{.Version}}
      - BUILT_BY=goreleaser
    hooks:
      pre:
        - ./build/webui.sh
        - ./build/innie.sh

archives:
  - id: releaseArchive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
  - id: releaseBinary
    formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

signs:
  - id: ed25519-sign
    cmd: selfupdatectl
    args:
      - "sign"
      - "--private-key=/dev/stdin"
      - "${artifact}"
    stdin: "{{ .Env.SELFUPDATE_SIGNING_KEY }}"
    signature: "${artifact}.ed25519"
    artifacts: all

release:
  github:
    owner: boldsoftware
    name: sketch
  draft: false
  prerelease: false

homebrew_casks:
  - name: sketch
    ids:
      - releaseArchive
    url:
      template: "https://github.com/boldsoftware/sketch/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      headers:
        - "Accept: application/octet-stream"
        - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    homepage: "https://sketch.dev"
    description: "Sketch is an agentic coding tool. It draws the 🦉"
    repository:
      owner: boldsoftware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
