name: WebUI Tests
on:
  workflow_call:
  push:
    branches-ignore:
      - "queue-main-**"
    paths:
      - 'loop/webui/**'
  pull_request:
    paths:
      - 'loop/webui/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: loop/webui/package-lock.json

      - name: Install dependencies
        working-directory: ./loop/webui
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./loop/webui
        run: npx playwright install --with-deps

      - name: Run tests
        working-directory: ./loop/webui
        run: npm run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: loop/webui/playwright-report/
          retention-days: 7
